version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cbkpermissionsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: topg
    ports:
      - "5432:5432" # Expose PostgreSQL port to the host
    networks:
      - per-app-net

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHOST: postgres
      PGDATABASE: cbkpermissionsdb
      PGUSER: postgres
      PGPASSWORD: topg
    volumes:
      - .:/app
    ports:
      - "5000:8080" # Expose Node.js app port to the host
    depends_on:
      - postgres
    networks:
      - per-app-net

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - per-app-net

networks:
  per-app-net:
    driver: bridge

